-- AlterTable
ALTER TABLE "pets" ADD COLUMN "is_lost" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "pets" ADD COLUMN "last_lat" DOUBLE PRECISION;
ALTER TABLE "pets" ADD COLUMN "last_lng" DOUBLE PRECISION;
